### ISSUE TITLE
Swift 4  / Xcode 9 - Out of date

### ISSUE THREAD

**Issue by foghel** [hyperoslo/Dropdown#3]
This project isn't compatible with Swift 4 / XCode 9 Release.

**Comment by onmyway133** [comment]
@foghel Hi, thanks for raising the issue. We're in the process of migrating our projects to swift 4. Will keep you posted once it's done

**Comment by onmyway133** [comment]
@foghel Hi, you can check new version https://github.com/hyperoslo/Dropdown/releases/tag/1.0.0 👍
